/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ControllerMusicaPlaylistPanel;
import Model.Musica;
import javax.swing.JOptionPane;

/**
 * Modelo de painel para as musicas das playlists
 * @author Acer Nitro 5
 */
public class MusicaPlaylistPanel extends javax.swing.JPanel {
    
    /**
     * Creates new form MusicaPlaylistPanel
     */
    public MusicaPlaylistPanel(Musica musica) {
        initComponents();
        c = new ControllerMusicaPlaylistPanel(this);
        this.ID_MUSICA = musica.getId();
        labelIdMusica.setText("ID: " + musica.getId());
        labelTitulo.setText(musica.getTitulo());
        labelGenero.setText(musica.getGenero());
        labelDuracao.setText("Duração: " + musica.getDuracao());
        labelArtista.setText(musica.getArtista());
        this.letra = musica.getLetra();
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoLetra = new javax.swing.JButton();
        botaoDescurtir = new javax.swing.JButton();
        botaoCurtir = new javax.swing.JButton();
        labelDuracao = new javax.swing.JLabel();
        labelGenero = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelIdMusica = new javax.swing.JLabel();
        labelArtista = new javax.swing.JLabel();
        botaoRemover = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botaoLetra.setText("LETRA");
        botaoLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLetraActionPerformed(evt);
            }
        });

        botaoDescurtir.setText("👎");
        botaoDescurtir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDescurtirActionPerformed(evt);
            }
        });

        botaoCurtir.setText("👍");
        botaoCurtir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCurtirActionPerformed(evt);
            }
        });

        labelDuracao.setText("DURACAO");

        labelGenero.setText("GENERO");

        labelTitulo.setText("TITULO");

        labelIdMusica.setText("ID:");

        labelArtista.setText("ARTISTA");

        botaoRemover.setText("Remover");
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelIdMusica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoRemover))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelArtista)
                            .addComponent(labelTitulo))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDuracao)
                            .addComponent(labelGenero))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(botaoCurtir)
                                .addGap(18, 18, 18)
                                .addComponent(botaoDescurtir)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(botaoLetra, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelIdMusica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(17, Short.MAX_VALUE)
                        .addComponent(botaoRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoDescurtir)
                    .addComponent(botaoCurtir)
                    .addComponent(labelTitulo)
                    .addComponent(labelDuracao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelArtista)
                    .addComponent(labelGenero)
                    .addComponent(botaoLetra))
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLetraActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, letra, "Letra da Música", JOptionPane.INFORMATION_MESSAGE);
        c.salvarHistorico(ID_MUSICA);
    }//GEN-LAST:event_botaoLetraActionPerformed

    private void botaoCurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCurtirActionPerformed
        // TODO add your handling code here:
        c.curtirMusica(ID_MUSICA);
    }//GEN-LAST:event_botaoCurtirActionPerformed

    private void botaoDescurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDescurtirActionPerformed
        // TODO add your handling code here:
        c.descurtirMusica(ID_MUSICA);
    }//GEN-LAST:event_botaoDescurtirActionPerformed

    private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoRemoverActionPerformed
    
    private String letra;
    private int ID_MUSICA;
    private ControllerMusicaPlaylistPanel c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCurtir;
    private javax.swing.JButton botaoDescurtir;
    private javax.swing.JButton botaoLetra;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JLabel labelArtista;
    private javax.swing.JLabel labelDuracao;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelIdMusica;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
