/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ControllerMusicas;
import Controller.ControllerMusicasPanel;
import Model.Sessao;
import Model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer Nitro 5
 */
public class MusicaPanel extends javax.swing.JPanel {

    /**
     * Creates new form MusicaPanel
     */
    public MusicaPanel() {
        initComponents();
        c = new ControllerMusicasPanel(this);
    }
    int ID_MUSICA;
    public void setTitulo(String titulo) {
        labelTitulo.setText( titulo);
    }

    public void setArtista(String artista) {
        labelArtista.setText(artista);
    }

    public void setGenero(String genero) {
        labelGenero.setText(genero);
    }

    public void setDuracao(int duracao) {
        labelDuracao.setText("Duração: " + duracao + "s");
    }
    public void setId(int id) {
        labelIdMusica.setText("ID: " + id);
        ID_MUSICA = id;
    }

    public void setLetra(String letra) {
        botaoLetra.addActionListener(e -> {
            JOptionPane.showMessageDialog(this, letra, "Letra da Música", JOptionPane.INFORMATION_MESSAGE);
         
            
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelArtista = new javax.swing.JLabel();
        labelGenero = new javax.swing.JLabel();
        labelDuracao = new javax.swing.JLabel();
        botaoLetra = new javax.swing.JButton();
        labelIdMusica = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelTitulo.setText("TITULO");

        labelArtista.setText("ARTISTA");

        labelGenero.setText("GENERO");

        labelDuracao.setText("DURACAO");

        botaoLetra.setText("LETRA");
        botaoLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLetraActionPerformed(evt);
            }
        });

        labelIdMusica.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo)
                    .addComponent(labelArtista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDuracao)
                        .addGap(18, 18, 18)
                        .addComponent(botaoLetra))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelGenero)
                        .addGap(42, 42, 42)
                        .addComponent(labelIdMusica)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoLetra)
                    .addComponent(labelDuracao)
                    .addComponent(labelTitulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelArtista)
                        .addComponent(labelGenero))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelIdMusica)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLetraActionPerformed
        // TODO add your handling code here:
        c.salvarHistorico(ID_MUSICA);
    }//GEN-LAST:event_botaoLetraActionPerformed

    private ControllerMusicasPanel c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoLetra;
    private javax.swing.JLabel labelArtista;
    private javax.swing.JLabel labelDuracao;
    private javax.swing.JLabel labelGenero;
    private javax.swing.JLabel labelIdMusica;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
