/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerPlaylist;
import Model.Musica;
import Model.Playlist;
import Model.Sessao;
import java.util.ArrayList;
import javax.swing.BoxLayout;

/**
 * Frame de uma Playlist x
 * @author Acer Nitro 5
 */
public class PlaylistFrame extends javax.swing.JFrame {

    /**
     * Creates new form PlaylistFrame
     */
    public PlaylistFrame(Playlist playlist) {
        initComponents();
        c = new ControllerPlaylist(this);
        txtTituloPlaylist.setText(playlist.getNome());
        mostrarMusicas(playlist.getMusicas());
        ID_PLAYLIST = playlist.getId_playlist();
    }
    private void mostrarMusicas(ArrayList<Musica> musicas) {
        painelMusicas.removeAll();
        painelMusicas.setLayout(new BoxLayout(painelMusicas, BoxLayout.Y_AXIS));

        for (Musica m : musicas) {
            MusicaPlaylistPanel mp = new MusicaPlaylistPanel(m);

            painelMusicas.add(mp);
        }

        painelMusicas.revalidate();
        painelMusicas.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTituloPlaylist = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        painelMusicas = new javax.swing.JPanel();
        botaoVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtAdicionar = new javax.swing.JTextField();
        boatoAdicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTituloPlaylist.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTituloPlaylist.setText("NOME_PLAYLIST");

        javax.swing.GroupLayout painelMusicasLayout = new javax.swing.GroupLayout(painelMusicas);
        painelMusicas.setLayout(painelMusicasLayout);
        painelMusicasLayout.setHorizontalGroup(
            painelMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        painelMusicasLayout.setVerticalGroup(
            painelMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(painelMusicas);

        botaoVoltar.setText("VOLTAR");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID MUSICA:");

        boatoAdicionar.setText("ADD");
        boatoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boatoAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoVoltar)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(txtTituloPlaylist)
                                .addGap(139, 139, 139))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boatoAdicionar)
                                .addGap(21, 21, 21))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltar)
                    .addComponent(jLabel1)
                    .addComponent(txtAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boatoAdicionar))
                .addGap(13, 13, 13)
                .addComponent(txtTituloPlaylist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // TODO add your handling code here:
        MenuFrame menu = new MenuFrame(Sessao.getUsuario());
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void boatoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boatoAdicionarActionPerformed
        // TODO add your handling code here:
        int id_musica_adicionada = Integer.parseInt(txtAdicionar.getText());
        c.adicionarMusica(id_musica_adicionada, this.ID_PLAYLIST);
        this.setVisible(false);
    }//GEN-LAST:event_boatoAdicionarActionPerformed


    private int ID_PLAYLIST;
    private ControllerPlaylist c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boatoAdicionar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelMusicas;
    private javax.swing.JTextField txtAdicionar;
    private javax.swing.JLabel txtTituloPlaylist;
    // End of variables declaration//GEN-END:variables
}
